# -*- coding: utf-8 -*-
"""Agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dkl5eEW5dgmh3ISWKVAtRWkcV38avF_4
"""



from google.colab import userdatacd 
userdata.get('task2')

pip install streamlit python-dotenv langchain langchain-community langchain-openai pypdf faiss-cpu qdrant-client

from google.colab import userdata
import os


os.environ["Task2"] = userdata.get("Task2")
os.environ["OPENAI_BASE_URL"] = "https://openrouter.ai/api/v1"
os.environ["MODEL_NAME"] = "openai/gpt-4o-mini"

from google.colab import userdata
import os


os.environ["Task2"] = userdata.get("Task2")
os.environ["OPENAI_BASE_URL"] = "https://openrouter.ai/api/v1"
os.environ["MODEL_NAME"] = "openai/gpt-4o-mini"

from google.colab import files
uploaded = files.upload()
pdf_path = list(uploaded.keys())[0]

from langchain_openai import ChatOpenAI
from langchain_community.document_loaders import PyPDFLoader
import os


agreement_type = input("Enter agreement type: ")


loader = PyPDFLoader(pdf_path)
pages = loader.load()


agreement_text = "\n".join([page.page_content for page in pages])


llm = ChatOpenAI(
    model=os.environ["MODEL_NAME"],
    base_url=os.environ["OPENAI_BASE_URL"],
    api_key=os.environ["Task2"]
)


prompt = f"""
You are an expert legal document analyzer.


Analyze this document as a {agreement_type}.


Document:
{agreement_text}


Return:
1. Document summary
2. Parties involved
3. Important clauses
4. Risky clauses
5. Missing clauses
6. Obligations of each party
7. Payment or penalty terms if any
8. Confidentiality terms if any
9. Termination conditions
10. Final risk rating: Low, Medium, or High
11. Practical recommendation


Do not give legal advice. Only provide an educational document analysis.
"""


response = llm.invoke(prompt)


print(response.content)

from google.colab import userdata
import os


os.environ["Task2"] = userdata.get("Task2")
os.environ["OPENAI_BASE_URL"] = "https://openrouter.ai/api/v1"
os.environ["MODEL_NAME"] = "openai/gpt-4o-mini"

from google.colab import files
uploaded = files.upload()
pdf_path = list(uploaded.keys())[0]

from langchain_openai import ChatOpenAI
from langchain_community.document_loaders import PyPDFLoader
import os


agreement_type = input("Enter agreement type: ")


loader = PyPDFLoader(pdf_path)
pages = loader.load()


agreement_text = "\n".join([page.page_content for page in pages])


llm = ChatOpenAI(
    model=os.environ["MODEL_NAME"],
    base_url=os.environ["OPENAI_BASE_URL"],
    api_key=os.environ["Task2"]
)


prompt = f"""
You are an expert legal document analyzer.


Analyze this document as a {agreement_type}.


Document:
{agreement_text}


Return:
1. Document summary
2. Parties involved
3. Important clauses
4. Risky clauses
5. Missing clauses
6. Obligations of each party
7. Payment or penalty terms if any
8. Confidentiality terms if any
9. Termination conditions
10. Final risk rating: Low, Medium, or High
11. Practical recommendation


Do not give legal advice. Only provide an educational document analysis.
"""


response = llm.invoke(prompt)


print(response.content)